### ISSUE TITLE
Walther MRS Reflex Sight rendering incorrectly + OKP-7 isn't centered

### ISSUE THREAD

**Issue by AerosunST** [dar-su/arc9_eft_ar15#1]
Walther MRS isn't rendering properly when aiming with front post (instead of absolute co-witness, the front post blocks it, which leads me to believe something isn't being layered properly)

OKP-7 is straight up just not aligned correctly in relation to the gas block front sight.

**Comment by dar-su** [comment]
![image](https://github.com/dar-su/arc9_eft_ar15/assets/95997959/e63a71ca-1517-4733-b0f8-b8b3ecf08bf9)
